# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='PositionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'positionList',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='listOFPositions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.PositionList'),
        ),
    ]
