# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_auto_20170502_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borough',
            old_name='voivodeship',
            new_name='region',
        ),
    ]
